# Generated by Django 4.2.4 on 2023-08-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tags_tagsarticle_tags_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag_name',
            new_name='name',
        ),
    ]
