# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 90dd43fcf14b4670c68b5c4782ab1530823a9d21

{
  "title": "Шкаф IKEA2",
  "description": "ТожеНеСрочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 90dd43fcf14b4670c68b5c4782ab1530823a9d21

{
  "status": "CLOSED"
}

###

GET {{baseUrl}}/advertisements/1/
Content-Type: application/json



###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1&status=OPEN
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
