# Generated by Django 4.2.4 on 2023-09-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
