# Generated by Django 4.2.4 on 2023-08-31 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_sensor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_id', to='measurement.sensor'),
        ),
    ]
