# Generated by Django 4.2.4 on 2023-09-01 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_rename_sensor_id_measurement_sensorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='sensorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.sensor'),
        ),
    ]
