# Generated by Django 4.2.4 on 2023-09-01 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_alter_measurement_sensorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='sensorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
