# Generated by Django 4.2.4 on 2023-09-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0010_alter_measurement_sensorid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
