# Generated by Django 4.2.4 on 2023-08-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0010_alter_measurement_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date_and_time',
            field=models.DateTimeField(),
        ),
    ]
