# Generated by Django 4.2.4 on 2023-08-31 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0011_alter_measurement_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.sensor'),
        ),
    ]
