# Generated by Django 4.2.4 on 2023-08-31 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0013_alter_sensor_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
